services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    restart: always
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/srv/gitlab-runner/config:/etc/gitlab-runner'
    networks:
      - gitlab-network
    environment:
      - CI_SERVER_URL=http://gitlab  # Внутренний URL GitLab
      - REGISTRATION_TOKEN=glrt-ms27Rss6mmVPs7vLirbJ
      - RUNNER_NAME=my-runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=docker:latest

  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    depends_on:
      - gitlab
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - gitlab-network

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonar_postgresql:/var/lib/postgresql
      - sonar_postgresql_data:/var/lib/postgresql/data
    networks:
      - gitlab-network

  nexus:
    image: sonatype/nexus3
    restart: always
    volumes: 
      - nexus-data:/sonatype-work
    ports:
      - "8081:8081"
      - "8085:8085"
    networks:
      - gitlab-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      MONGO_INITDB_ROOT_USERNAME: seeu
      MONGO_INITDB_ROOT_PASSWORD: fa2372cd
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - ./data:/data
    ports:
      - 9002:9000
      - 9003:9001
    environment:
      MINIO_ROOT_USER: 'seeu359'
      MINIO_ROOT_PASSWORD: 'password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

networks:
  gitlab-network:
    external: true

volumes:
  nexus-data: {}
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonar_postgresql:
  sonar_postgresql_data:

