services:
  loadbalancer:
    image: nginxproxy/nginx-proxy:1.5
    ports:
      - "8003:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=test2

  web:
    image: katacoda/docker-http-server:healthy
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=test2 
