---
- hosts: all
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      become: yes
  
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes
    
    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      become: yes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: Add docker repository
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true
      become: yes

    - name: Setup docker user
      ansible.builtin.user:
        name: docker
        groups: "docker,sudo"
        append: true
      become: true

    - name: Install Docker-Compose&Set Permission
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'
      become: yes

    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true
      become: yes
